USE [Plants]
GO

/****** Object:  Table [dbo].[LightLevel]    Script Date: 11/10/2024 12:17:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE [dbo].[LightLevel]
GO

CREATE TABLE [dbo].[LightLevel](
	[LightLevelID] [int] IDENTITY(1,1) NOT NULL,
	[LightLevel] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_LightLevel] PRIMARY KEY CLUSTERED 
(
	[LightLevelID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

